'use client';

/**
 * FlagshipAppSection — pale light-world flagship product section
 * (landing premium pass, founder build-list #3).
 *
 * Pattern transfer (choreography.md §2, founder-shots): a pale-world section,
 * centered eyebrow + serif title, then a large product screenshot of OUR app
 * (the vault marketplace) framed in a dark rounded frame with shadow-modal —
 * the editorial "here is the thing" beat after the hero.
 *
 * The screenshot is a real capture of apps/app marketplace (flagship-app.png,
 * generated by reference-lab/src/flagship-shot.ts at 1440×900) — our own
 * surface, not a benchmark asset. <Image> with explicit dimensions = CLS 0.
 *
 * Motion: ONE restrained whileInView reveal (opacity + translateY ≤16px),
 * tokens only. Transform/opacity. prefers-reduced-motion = instant.
 */

import Image from 'next/image';
import { motion, useReducedMotion } from 'motion/react';
import { DURATIONS_S, EASE_ENTER } from '@metador/design-system';

const FLAGSHIP_W = 1440;
const FLAGSHIP_H = 900;

export function FlagshipAppSection() {
  const reducedMotion = useReducedMotion();
  const dy = reducedMotion ? 0 : 16;

  return (
    <section
      id="flagship-app"
      aria-labelledby="flagship-heading"
      data-theme="light"
      style={{
        position: 'relative',
        padding: 'var(--metador-space-24) var(--metador-space-4)',
        backgroundColor: 'var(--metador-bg)',
        overflow: 'hidden',
      }}
    >
      {/* Glow-bleed seam at dark→light entry (elevation-spec §2.4) */}
      <div className="metador-seam metador-seam--top" aria-hidden="true" />

      <div
        style={{
          maxWidth: 1120,
          margin: '0 auto',
          width: '100%',
        }}
      >
        {/* Centered eyebrow + serif title */}
        <motion.div
          initial={{ opacity: 0, y: dy }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-80px' }}
          transition={{ duration: DURATIONS_S.slow, ease: EASE_ENTER }}
          style={{
            textAlign: 'center',
            marginBottom: 'var(--metador-space-12)',
          }}
        >
          <p
            className="metador-eyebrow"
            style={{ marginBottom: 'var(--metador-space-4)' }}
          >
            The product
          </p>
          <h2
            id="flagship-heading"
            className="metador-display"
            style={{
              fontFamily: 'var(--metador-font-display)',
              fontSize: 'clamp(2.5rem, 3vw + 1rem, 3.5rem)',
              lineHeight: 1.05,
              color: 'var(--metador-text)',
              letterSpacing: '-0.02em',
              maxWidth: '20ch',
              marginInline: 'auto',
            }}
          >
            Every wall, visible before you deposit.
          </h2>
          <p
            style={{
              fontFamily: 'var(--metador-font-text)',
              fontSize: 'var(--metador-text-base)',
              lineHeight: 'var(--metador-text-base--line-height)',
              color: 'var(--metador-muted)',
              maxWidth: '54ch',
              marginInline: 'auto',
              marginTop: 'var(--metador-space-4)',
            }}
          >
            The marketplace shows each vault&apos;s budget meter, scope, and live
            status — including the ones that have been revoked. The proof is on the
            screen, not in a pitch.
          </p>
        </motion.div>

        {/* Dark rounded frame holding the real product screenshot.
            data-theme="dark" re-asserts the dark ramp inside this pale section
            so the frame chrome uses tokens (no raw hex) — the app lives dark. */}
        <motion.div
          data-theme="dark"
          initial={{ opacity: 0, y: reducedMotion ? 0 : 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-60px' }}
          transition={{ duration: DURATIONS_S.hero, ease: EASE_ENTER, delay: 0.06 }}
          style={{
            backgroundColor: 'var(--metador-bg)',
            border: '1px solid var(--metador-border)',
            borderRadius: 'var(--metador-radius-xl)',
            boxShadow: 'var(--metador-shadow-modal)',
            padding: 'var(--metador-space-2)',
            overflow: 'hidden',
          }}
        >
          <Image
            src="/flagship-app.png"
            alt="Metador vault marketplace — budget meters, scope, and live status for every vault, including revoked vaults."
            width={FLAGSHIP_W}
            height={FLAGSHIP_H}
            priority={false}
            sizes="(max-width: 1120px) 100vw, 1120px"
            style={{
              display: 'block',
              width: '100%',
              height: 'auto',
              borderRadius: 'calc(var(--metador-radius-xl) - var(--metador-space-2))',
            }}
          />
        </motion.div>
      </div>
    </section>
  );
}
